# Prometheus configuration for Saga Examples monitoring

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: saga-examples
    environment: development

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: prometheus

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: postgresql
          database: saga

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: redis

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: rabbitmq

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          service: jaeger

  # Grafana metrics (self-monitoring)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: grafana
    metrics_path: /metrics

# Service discovery for Docker containers with prometheus labels
  - job_name: 'docker-services'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_docker_container_label_prometheus_io_port]
        action: replace
        regex: (.+)
        target_label: __address__
        replacement: $1
      - source_labels: [__meta_docker_container_label_prometheus_io_path]
        action: replace
        regex: (.+)
        target_label: __metrics_path__
        replacement: $1
      - source_labels: [__meta_docker_container_name]
        action: replace
        regex: /(.+)
        target_label: container

