server:
  name: "payment-service"
  version: "1.0.0"
  grpc_port: "9082"

tracing:
  enabled: true
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "payment-service"
  sampling_rate: 1.0

payment:
  simulation_mode: true
  timeout: "30s"
  failure_rate: 0.1
  processing_time: "2s"

logging:
  level: "info"
  format: "json"