version: 2

# 仅启用 GitHub Actions 常规版本更新。
# Go / 其他生态的常规版本更新已关闭，仍然会收到：
#  - Dependabot Security Updates（若开启仓库安全设置）
#  - GitHub Advisory Database 中涉及到的安全补丁 PR
# 如需恢复 Go 模块或其他生态更新，在下方添加相应条目即可。
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "03:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore"
      include: "scope"
