version: 2
updates:
  # Go Modules updates (root go.mod)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "03:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Docker (for Dockerfiles)
  - package-ecosystem: "docker"
    directory: "/build/docker"
    schedule:
      interval: weekly
      day: "sunday"
      time: "04:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      include: "scope"

  # NPM dependencies for docs site if present
  - package-ecosystem: "npm"
    directory: "/docs/pages"
    schedule:
      interval: weekly
      day: "monday"
      time: "05:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docs"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "playwright*"
        update-types: ["version-update:semver-major"]

  # Go modules for examples folder (if separate go.mod files exist)
  - package-ecosystem: "gomod"
    directory: "/examples/full-featured-service"
    schedule:
      interval: weekly
      day: "tuesday"
      time: "02:30"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "examples"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
