database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  dbname: user_service_db

server:
  port: 9000
  # HTTP Configuration with secure CORS settings
  http:
    enabled: true
    port: "9000"
    middleware:
      enable_cors: true
      cors:
        # SECURITY: Specify explicit allowed origins instead of wildcard
        # For development, use specific localhost ports
        # For production, use your actual frontend domains
        allow_origins:
          - "http://localhost:3000"    # React/Vue dev server
          - "http://localhost:8080"    # Alternative frontend port
          - "https://your-domain.com"  # Production frontend (update this)
        allow_methods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        allow_headers:
          - "Origin"
          - "Content-Type"
          - "Accept"
          - "Authorization"
        allow_credentials: true
        max_age: 86400  # 24 hours

# Distributed Tracing Configuration
tracing:
  enabled: true
  service_name: "swit-serve"
  sampling:
    type: "traceidratio"
    rate: 1.0  # Full sampling for development
  exporter:
    type: "jaeger"
    endpoint: "http://localhost:14268/api/traces"
    timeout: "10s"
  resource_attributes:
    environment: "development"
    version: "v1.0.0"
    service.namespace: "swit"
  propagators:
    - "tracecontext"
    - "baggage"

# Messaging Configuration (Event-Driven Architecture)
messaging:
  enabled: false  # Enable when using event-driven patterns
  default_broker: "local"
  
  # Broker configurations
  brokers:
    local:
      type: "inmemory"
    
    # Example Kafka configuration (uncomment and configure as needed)
    # kafka:
    #   type: "kafka"
    #   endpoints:
    #     - "localhost:9092"
    #   authentication:
    #     type: "none"
    #   tls:
    #     enabled: false
    
    # Example NATS configuration (uncomment and configure as needed)
    # nats:
    #   type: "nats"
    #   endpoints:
    #     - "nats://localhost:4222"
    #   authentication:
    #     type: "none"
  
  # Global connection settings
  connection:
    timeout: "30s"
    keep_alive: "30s"
    max_attempts: 3
    retry_interval: "5s"
    pool_size: 10
    idle_timeout: "5m"
  
  # Security settings
  security:
    enable_encryption: false
    enable_authentication: false
    enable_authorization: false
    message_signing: false
  
  # Performance tuning
  performance:
    batch_size: 100
    batch_timeout: "100ms"
    buffer_size: 1000
    concurrency: 1
    prefetch_count: 10
    compression_enabled: false
  
  # Monitoring and observability
  monitoring:
    enabled: true
    metrics_enabled: true
    tracing_enabled: false
    health_check_enabled: true
    health_check_interval: "30s"

# Access Control (RBAC) Configuration
access_control:
  enabled: false
  strict_mode: false
  super_admin_role: ""
  default_roles: []
  resource_separator: ":"

  # Define permissions registry (optional). You can also reference inline patterns like "orders:read"
  permissions:
    # example_view:
    #   description: "View example resource"
    #   resource: "example"
    #   action: "view"
    #   is_system: true

  # Define roles and their permissions (names or inline patterns) and inheritance
  roles:
    # reader:
    #   description: "Read-only access"
    #   permissions: ["example:view", "orders:read"]
    #   inherits: []
    #   is_system: false
    # admin:
    #   description: "Administrator"
    #   permissions: ["*"]  # Grant via inline wildcard patterns if your enforcement supports it
    #   inherits: ["reader"]
    #   is_system: true

# Security Configuration
security:
  enabled: false  # Enable security features (OAuth2, OPA, Audit, etc.)
  
  # OAuth2/OIDC Configuration
  oauth2:
    enabled: false
    provider: "keycloak"  # keycloak, auth0, okta, google, etc.
    issuer_url: "https://auth.example.com/realms/demo"
    client_id: "${OAUTH2_CLIENT_ID}"
    client_secret: "${OAUTH2_CLIENT_SECRET}"
    # Optional: Redirect URL for OAuth2 flow
    # redirect_url: "http://localhost:8080/callback"
    # Optional: Scopes to request
    # scopes: ["openid", "profile", "email"]
  
  # OPA (Open Policy Agent) Configuration
  opa:
    mode: "embedded"  # embedded or remote
    policy_dir: "./policies"  # Directory containing .rego policy files
    # For remote mode:
    # server_url: "http://localhost:8181"
    # Optional: Default decision path
    # decision_path: "/v1/data/authz/allow"
  
  # Security Scanner Configuration
  scanner:
    enabled: false
    tools: []  # e.g., ["gosec", "trivy"]
    # Optional: Scanner-specific settings
    # scan_interval: "24h"
  
  # Secrets Management Configuration
  secrets:
    provider: "env"  # env, vault, aws-secrets-manager, gcp-secret-manager
    # For Vault:
    # vault_address: "http://localhost:8200"
    # vault_token: "${VAULT_TOKEN}"
    # For AWS Secrets Manager:
    # aws_region: "us-west-2"
  
  # Audit Logging Configuration
  audit:
    enabled: false
    output_type: "stdout"  # stdout, file, or syslog
    # For file output:
    # file_path: "/var/log/security-audit.log"
    # Optional: Log format
    # format: "json"  # json or text
    # Optional: Log rotation
    # max_size_mb: 100
    # max_backups: 3
    # max_age_days: 30

serviceDiscovery:
  address: "localhost:8500"
