database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  dbname: user_service_db

server:
  port: 9000
  # HTTP Configuration with secure CORS settings
  http:
    enabled: true
    port: "9000"
    middleware:
      enable_cors: true
      cors:
        # SECURITY: Specify explicit allowed origins instead of wildcard
        # For development, use specific localhost ports
        # For production, use your actual frontend domains
        allow_origins:
          - "http://localhost:3000"    # React/Vue dev server
          - "http://localhost:8080"    # Alternative frontend port
          - "https://your-domain.com"  # Production frontend (update this)
        allow_methods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        allow_headers:
          - "Origin"
          - "Content-Type"
          - "Accept"
          - "Authorization"
        allow_credentials: true
        max_age: 86400  # 24 hours

# Distributed Tracing Configuration
tracing:
  enabled: true
  service_name: "swit-serve"
  sampling:
    type: "traceidratio"
    rate: 1.0  # Full sampling for development
  exporter:
    type: "jaeger"
    endpoint: "http://localhost:14268/api/traces"
    timeout: "10s"
  resource_attributes:
    environment: "development"
    version: "v1.0.0"
    service.namespace: "swit"
  propagators:
    - "tracecontext"
    - "baggage"

# Messaging Configuration (Event-Driven Architecture)
messaging:
  enabled: false  # Enable when using event-driven patterns
  default_broker: "local"
  
  # Broker configurations
  brokers:
    local:
      type: "inmemory"
    
    # Example Kafka configuration (uncomment and configure as needed)
    # kafka:
    #   type: "kafka"
    #   endpoints:
    #     - "localhost:9092"
    #   authentication:
    #     type: "none"
    #   tls:
    #     enabled: false
    
    # Example NATS configuration (uncomment and configure as needed)
    # nats:
    #   type: "nats"
    #   endpoints:
    #     - "nats://localhost:4222"
    #   authentication:
    #     type: "none"
  
  # Global connection settings
  connection:
    timeout: "30s"
    keep_alive: "30s"
    max_attempts: 3
    retry_interval: "5s"
    pool_size: 10
    idle_timeout: "5m"
  
  # Security settings
  security:
    enable_encryption: false
    enable_authentication: false
    enable_authorization: false
    message_signing: false
  
  # Performance tuning
  performance:
    batch_size: 100
    batch_timeout: "100ms"
    buffer_size: 1000
    concurrency: 1
    prefetch_count: 10
    compression_enabled: false
  
  # Monitoring and observability
  monitoring:
    enabled: true
    metrics_enabled: true
    tracing_enabled: false
    health_check_enabled: true
    health_check_interval: "30s"

serviceDiscovery:
  address: "localhost:8500"
