server:
  name: "order-service"
  version: "1.0.0"
  http_port: "8081"
  grpc_port: "9081"

database:
  driver: "sqlite"
  dsn: "./data/orders.db"

tracing:
  enabled: true
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "order-service"
  sampling_rate: 1.0

external_services:
  payment_service_url: "localhost:9082"
  inventory_service_url: "localhost:9083"
  timeout: "30s"

logging:
  level: "info"
  format: "json"