apiVersion: v1
kind: ConfigMap
metadata:
  name: swit-config
  namespace: swit
  labels:
    app: swit-platform
data:
  # MySQL 配置
  MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
  MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
  
  # 数据库连接配置
  DATABASE_HOST: "mysql-service"
  DATABASE_PORT: "3306"
  DATABASE_USERNAME: "root"
  
  # 服务端口配置
  AUTH_SERVER_PORT: "9001"
  MAIN_SERVER_PORT: "9000"
  
  # 服务发现配置
  SERVICE_DISCOVERY_ADDRESS: "consul-service:8500"
  
  # 数据库名称
  AUTH_DATABASE_DBNAME: "auth_service_db"
  MAIN_DATABASE_DBNAME: "user_service_db"
  
  # 服务 URL
  AUTH_SERVICE_URL: "http://swit-auth-service:9001"
  
  # 日志级别
  LOG_LEVEL: "info"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: swit-auth-config
  namespace: swit
  labels:
    app: swit-auth
data:
  switauth.yaml: |
    database:
      host: mysql-service
      port: 3306
      username: root
      password: root
      dbname: auth_service_db
    server:
      port: 9001
    serviceDiscovery:
      address: "consul-service:8500"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: swit-serve-config
  namespace: swit
  labels:
    app: swit-serve
data:
  swit.yaml: |
    database:
      host: mysql-service
      port: 3306
      username: root
      password: root
      dbname: user_service_db
    server:
      port: 9000
    serviceDiscovery:
      address: "consul-service:8500" 