apiVersion: v1
kind: Secret
metadata:
  name: swit-secret
  namespace: swit
  labels:
    app: swit-platform
type: Opaque
data:
  # 数据库密码 (base64 编码的 "root")
  DATABASE_PASSWORD: cm9vdA==
  MYSQL_ROOT_PASSWORD: cm9vdA==
  
  # JWT 密钥 (base64 编码的 "swit-jwt-secret-key")
  JWT_SECRET: c3dpdC1qd3Qtc2VjcmV0LWtleQ== 