server:
  name: "inventory-service"
  version: "1.0.0"
  http_port: "8083"
  grpc_port: "9083"

tracing:
  enabled: true
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "inventory-service"
  sampling_rate: 1.0

logging:
  level: "info"
  format: "json"