{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "swit.mysql.fullname" . }}-service
  namespace: {{ include "swit.namespace" . }}
  labels:
    {{- include "swit.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "swit.mysql.selectorLabels" . | nindent 4 }}
{{- end }} 