basePath: /
definitions:
  github_com_innovationmech_swit_internal_switauth_model.ErrorResponse:
    properties:
      error:
        example: Invalid credentials
        type: string
    type: object
  github_com_innovationmech_swit_internal_switauth_model.HealthResponse:
    properties:
      message:
        example: pong
        type: string
    type: object
  github_com_innovationmech_swit_internal_switauth_model.LoginRequest:
    properties:
      password:
        example: password123
        minLength: 6
        type: string
      username:
        example: john_doe
        type: string
    required:
    - password
    - username
    type: object
  github_com_innovationmech_swit_internal_switauth_model.LoginResponse:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  github_com_innovationmech_swit_internal_switauth_model.LogoutResponse:
    properties:
      message:
        example: Logged out successfully
        type: string
    type: object
  github_com_innovationmech_swit_internal_switauth_model.RefreshTokenRequest:
    properties:
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    required:
    - refresh_token
    type: object
  github_com_innovationmech_swit_internal_switauth_model.RefreshTokenResponse:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  github_com_innovationmech_swit_internal_switauth_model.ValidateTokenResponse:
    properties:
      message:
        example: Token is valid
        type: string
      user_id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
    type: object
host: localhost:8090
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the SWIT authentication service API documentation.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: SWIT Auth API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user with username and password, returns access
        and refresh tokens
      parameters:
      - description: User login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.LoginResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.ErrorResponse'
        "401":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.ErrorResponse'
      summary: User login
      tags:
      - authentication
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Invalidate the user's access token and log them out
      produces:
      - application/json
      responses:
        "200":
          description: Logout successful
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.LogoutResponse'
        "400":
          description: Authorization header is missing
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: User logout
      tags:
      - authentication
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Generate new access and refresh tokens using a valid refresh token
      parameters:
      - description: Refresh token
        in: body
        name: refresh
        required: true
        schema:
          $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Token refresh successful
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.RefreshTokenResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.ErrorResponse'
        "401":
          description: Invalid or expired refresh token
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.ErrorResponse'
      summary: Refresh access token
      tags:
      - authentication
  /auth/validate:
    get:
      consumes:
      - application/json
      description: Validate an access token and return token information including
        user ID
      produces:
      - application/json
      responses:
        "200":
          description: Token is valid
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.ValidateTokenResponse'
        "401":
          description: Invalid or expired token
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Validate access token
      tags:
      - authentication
  /health:
    get:
      consumes:
      - application/json
      description: Check if the authentication service is healthy
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            $ref: '#/definitions/github_com_innovationmech_swit_internal_switauth_model.HealthResponse'
      summary: Health check
      tags:
      - health
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
