name: Dependabot Auto Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write
  issues: write  # 需要创建/添加标签

# 只针对 dependabot PR
jobs:
  automerge:
    if: >-
      github.actor == 'dependabot[bot]' ||
      (github.event.pull_request.user.login == 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add labels (semver / security)
        if: steps.metadata.outputs.update-type != ''
        uses: actions-ecosystem/action-add-labels@v1
        continue-on-error: true
        with:
          labels: |
            dependencies
            ${{ steps.metadata.outputs.update-type }}
            ${{ steps.metadata.outputs.security-advisory-id != '' && 'security' || '' }}

      - name: Auto approve security update
        if: steps.metadata.outputs.security-advisory-id != ''
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto merge for security update
        if: steps.metadata.outputs.security-advisory-id != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      - name: Comment on non-security update
        if: steps.metadata.outputs.security-advisory-id == ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.issues.createComment({
              ...context.repo,
              issue_number: pr.number,
              body: 'ℹ️ 此 Dependabot PR 为常规版本更新（非安全），已禁用自动合并，请人工评估。'
            });
