name: Dependabot Auto Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

# 只针对 dependabot PR
jobs:
  automerge:
    if: >-
      github.actor == 'dependabot[bot]' ||
      (github.event.pull_request.user.login == 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add semver scope label
        if: steps.metadata.outputs.update-type != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            dependencies
            ${{ steps.metadata.outputs.update-type }}

      - name: Auto approve patch/minor
        if: contains(steps.metadata.outputs.update-type, 'version-update:semver-patch') || contains(steps.metadata.outputs.update-type, 'version-update:semver-minor')
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto merge for patch/minor
        if: contains(steps.metadata.outputs.update-type, 'version-update:semver-patch') || contains(steps.metadata.outputs.update-type, 'version-update:semver-minor')
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      - name: Merge PR if eligible
        if: contains(steps.metadata.outputs.update-type, 'version-update:semver-patch') || contains(steps.metadata.outputs.update-type, 'version-update:semver-minor')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const { data: updated } = await github.pulls.get({ ...context.repo, pull_number: pr.number });
            if (updated.mergeable_state === 'clean') {
              await github.pulls.merge({
                ...context.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              core.info(`Merged Dependabot PR #${pr.number}`);
            } else {
              core.info(`PR #${pr.number} not mergeable state: ${updated.mergeable_state}`);
            }

      - name: Comment on major update
        if: contains(steps.metadata.outputs.update-type, 'version-update:semver-major')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.issues.createComment({
              ...context.repo,
              issue_number: pr.number,
              body: '⚠️ 这是一个 **major** 版本更新，请人工审核后再合并。'
            });
